Repository andes/mobile-app, pull requests merged in 2024-05, with the labels that each got.

#193 RUP - Error en Adjuntos RUP
  src/providers/auth/device.ts
Labels: request changes

#199 AM - Cambiar edad para usar perfil Hijo
  src/app/pages/mis-familiares/mis-familiares.page.html
  src/app/pages/mis-familiares/mis-familiares.page.ts
  src/app/pages/mis-familiares/registro-familiar.html
Labels: test ok

#200 AM - Editar domicilio paciente
  src/app/pages/profile/paciente/contacto/profile-contacto.html
  src/app/pages/profile/paciente/contacto/profile-contacto.ts
  src/app/pages/profile/paciente/donde-vivo-donde-trabajo/donde-vivo-donde-trabajo.html
  src/app/pages/profile/paciente/donde-vivo-donde-trabajo/donde-vivo-donde-trabajo.ts
  src/app/pages/profile/paciente/profile-paciente/profile-paciente.html
  src/app/pages/profile/paciente/profile-paciente/profile-paciente.scss
  src/app/pages/profile/paciente/profile-paciente/profile-paciente.ts
  src/app/pages/profile/paciente/tab-view-profile.html
  src/providers/toast.ts
Labels: test ok, publicar

#202 fix(AM): Cambia mensaje al no encontrar turnos disponibles
  src/app/pages/turnos/prestaciones/turnos-prestaciones.html
Labels: publicar
